import subprocess

print("Creating .csv file...")
subprocess.run(["python3", "makeCSV.py"])
print("File created. Appending file...")
subprocess.run(["python3", "appendCSV2.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendCSV3.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendCSV4.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendCSV5.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendCSV6.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendCSV7.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendCSV8.py"])
print("Process finished...")