import subprocess

print("Creating .csv file...")
subprocess.run(["python3", "makeCSVindirect.py"])
print("File created. Appending file...")
subprocess.run(["python3", "appendiCSV2.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendiCSV3.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendiCSV4.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendiCSV5.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendiCSV6.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendiCSV7.py"])
print("Appended a file. Appending next file...")
subprocess.run(["python3", "appendiCSV8.py"])
print("Process finished...")